check: boot-check boot-smt-check qemu-boot-check debian-jessie-boot-check

boot-check: skiboot.lid
	$(call Q, BOOT TEST , ./test/run_mambo_boot_test.sh, $@)

boot-smt-check: skiboot.lid
	$(call Q, BOOT TEST , THREADS=2 ./test/run_mambo_boot_test.sh, $@)

qemu-boot-check: skiboot.lid
	$(call Q, BOOT TEST , ./test/run_qemu_boot_test.sh , $@)

debian-jessie-boot-check: skiboot.lid
	$(call Q, BOOT TEST , ./test/run_qemu-jessie-debian-installer_boot_test.sh, $@)

OP_BUILD_BOOT_CHECK=op-build-v1.0 op-build-v1.1 op-build-v1.2 op-build-v1.2.1

boot-check-%: skiboot.lid skiboot.map
	$(call Q, BOOT TEST , SKIBOOT_MEM_DUMP=skiboot-$(@:boot-check-%=%).dump SKIBOOT_ZIMAGE=`pwd`/opal-ci/images/$(@:boot-check-%=%)/zImage.epapr ./test/run_mambo_boot_test.sh, $@)

boot-tests: boot-check $(OP_BUILD_BOOT_CHECK:%=boot-check-%)

boot-coverage-report: boot-tests extract-gcov skiboot.map all-boot-hardware
	$(call Q, BOOT TEST , CROSS=$(CROSS) BOOT_TESTS="hello_world boot_test ${OP_BUILD_BOOT_CHECK} ${FSP_GCOV_MACHINES}" ./test/make-boot-coverage-report.sh, $@)

boot-fsp-hardware-%: skiboot.lid skiboot.map
	$(call Q, BOOT TEST , ./external/boot-tests/boot_test.sh -v -p -b fsp -t $(@:boot-fsp-hardware-%=%) -1 skiboot.lid, $@)
	./external/boot-tests/extract_gcov.sh $(@:boot-fsp-hardware-%=%)

all-boot-hardware: $(FSP_GCOV_MACHINES:%=boot-fsp-hardware-%)
