# -*-Makefile-*-

SUBDIRS += hdata
HDATA_OBJS = spira.o paca.o pcia.o hdif.o memory.o fsp.o iohub.o vpd.o slca.o
HDATA_OBJS += cpu-common.o vpd-common.o hostservices.o
DEVSRC_OBJ = hdata/built-in.o

$(DEVSRC_OBJ): $(HDATA_OBJS:%=hdata/%)
